#index:
#    path: /
#    controller: App\Controller\DefaultController::index
PostUser:
  path:       /user/index
  controller: App\Controller\UserController::index
  methods:    POST
  
ShowUser:
  path:       /user/show/{id}
  controller: App\Controller\UserController::show
  methods:    GET

#GetLuckyNumber:
#    path:       /lucky/number/{max}
#   controller: App\Controller\LuckyController::number
#    methods:    GET

PostComment:
  path:       /comment/index
  controller: App\Controller\CommentController::index
  methods:    POST

ShowComment:
  path:       /comment/show/{id}
  controller: App\Controller\CommentController::show
  methods:    GET

PostContainer:
  path:       /container/index
  controller: App\Controller\ContainerController::index
  methods:    POST

ShowContainer:
  path:       /container/show/{id}
  controller: App\Controller\ContainerController::show
  methods:    GET